# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='nombre')),
                ('branch', models.CharField(blank=True, max_length=32, verbose_name='marca')),
                ('model', models.CharField(blank=True, max_length=32, verbose_name='modelo')),
                ('description', models.CharField(max_length=128, verbose_name='descripción')),
                ('daily_lease_price', models.PositiveIntegerField(verbose_name='precio de arriendo diario')),
                ('stock', models.PositiveIntegerField(verbose_name='inventario')),
                ('stock_available', models.PositiveIntegerField(verbose_name='inventario disponible')),
            ],
        ),
        migrations.CreateModel(
            name='Leasing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_record', models.DateTimeField(verbose_name='fecha/hora de registro')),
                ('return_record', models.DateTimeField(verbose_name='fecha/hora de entrega')),
                ('total_price', models.PositiveIntegerField(verbose_name='precio total')),
                ('return_date', models.DateField(verbose_name='fecha de devolución')),
                ('returned', models.BooleanField(verbose_name='devueltomak')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Client', verbose_name='cliente')),
            ],
        ),
        migrations.CreateModel(
            name='LeasingEquipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='cantidad')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Equipment', verbose_name='equipamiento')),
                ('leasing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Leasing', verbose_name='arriendo')),
            ],
        ),
        migrations.AddField(
            model_name='leasing',
            name='equipments',
            field=models.ManyToManyField(through='equipment_rental.LeasingEquipments', to='equipment_rental.Equipment', verbose_name='equipamientos'),
        ),
    ]
