# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasing',
            name='return_record',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha/hora de entrega'),
        ),
        migrations.AlterField(
            model_name='leasing',
            name='returned',
            field=models.BooleanField(default=False, verbose_name='devueltomak'),
        ),
    ]
