# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_rental', '0002_auto_20170515_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad_cultural',
            fields=[
                ('ad_cultural_id', models.AutoField(primary_key=True, serialize=False)),
                ('componentes', models.CharField(max_length=32, verbose_name='componente')),
            ],
        ),
        migrations.CreateModel(
            name='Agentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, verbose_name='Agente')),
                ('importancia', models.CharField(max_length=32, verbose_name='Importancia')),
            ],
        ),
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('autor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, verbose_name='Autor')),
                ('email', models.CharField(max_length=32, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='Camino',
            fields=[
                ('camino_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, verbose_name='nombre camino')),
            ],
        ),
        migrations.CreateModel(
            name='distancia_camino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.PositiveIntegerField(verbose_name='distancia')),
                ('camino_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Camino', verbose_name='camino')),
            ],
        ),
        migrations.CreateModel(
            name='distancia_fuente_agua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.PositiveIntegerField(verbose_name='distancia')),
                ('nombre', models.CharField(max_length=32, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Distribucion_espacial',
            fields=[
                ('distribucion_espacial_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, verbose_name='Distribucion espacial')),
            ],
        ),
        migrations.CreateModel(
            name='Emplazamiento_geo',
            fields=[
                ('emplazamiento_geo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, verbose_name='Emplazamiento geomorfologico')),
            ],
        ),
        migrations.CreateModel(
            name='Emplazamiento_sitio',
            fields=[
                ('emplazamiento_sitio_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, verbose_name='Emplazamiento sitio')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('evaluacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, verbose_name='Evaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Financiamiento',
            fields=[
                ('financiamiento_id', models.AutoField(primary_key=True, serialize=False)),
                ('proyecto', models.CharField(max_length=32, verbose_name='proyecto')),
                ('descripcion', models.CharField(max_length=32, verbose_name='descripcion')),
                ('area', models.CharField(max_length=32, verbose_name='area')),
            ],
        ),
        migrations.CreateModel(
            name='Financiamiento_Instituciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.PositiveIntegerField(verbose_name='monto')),
                ('financimiento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Financiamiento', verbose_name='financiamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Funcion_inferida',
            fields=[
                ('inferida_if', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, verbose_name='Funcion inferida')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen_objeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('imagenes_id', models.AutoField(primary_key=True, serialize=False)),
                ('ruta', models.CharField(max_length=32, verbose_name='Ruta imagen')),
                ('formato', models.CharField(max_length=32, verbose_name='Formato imagen')),
                ('autor', models.CharField(default='Desconocido', max_length=32, verbose_name='autor')),
                ('descripcion', models.CharField(default='Desconocido', max_length=32, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Impacto',
            fields=[
                ('impacto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, verbose_name='Impacto')),
            ],
        ),
        migrations.CreateModel(
            name='Instituciones',
            fields=[
                ('institucion_id', models.AutoField(primary_key=True, serialize=False)),
                ('institucion', models.CharField(max_length=32, verbose_name='Institucion')),
                ('direccion', models.CharField(max_length=32, verbose_name='direccion')),
                ('ciudad', models.CharField(max_length=32, verbose_name='ciudad')),
                ('pais', models.CharField(max_length=32, verbose_name='pais')),
                ('sitio_web', models.CharField(max_length=32, verbose_name='sitio web')),
            ],
        ),
        migrations.CreateModel(
            name='Instituciones_Autores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Autores', verbose_name='Autor')),
                ('institucion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Instituciones', verbose_name='institucion')),
            ],
        ),
        migrations.CreateModel(
            name='Instituciones_registrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Instituciones', verbose_name='institucion')),
            ],
        ),
        migrations.CreateModel(
            name='Instrumentos',
            fields=[
                ('instrumentos_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, verbose_name='Instrumentos')),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('localidad_id', models.AutoField(primary_key=True, serialize=False, verbose_name='localidad_id')),
                ('nombre_loc', models.CharField(max_length=32, verbose_name='Localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Naturaleza',
            fields=[
                ('naturaleza_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, verbose_name='Naturaleza')),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('objeto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, verbose_name='Objeto')),
                ('descripcion', models.CharField(max_length=32, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('periodo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, verbose_name='Periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Por_alteracion',
            fields=[
                ('alteracion_id', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje', models.CharField(max_length=32, verbose_name='Porcentaje de alteracion')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('prov_id', models.AutoField(primary_key=True, serialize=False, verbose_name='prov_id')),
                ('nombre', models.CharField(max_length=32, verbose_name='Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia_biotica',
            fields=[
                ('prov_bio_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, verbose_name='Provincia Biótica')),
            ],
        ),
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbi', models.CharField(max_length=32, verbose_name='dbi')),
                ('titulo', models.CharField(max_length=32, verbose_name='titulo')),
                ('año', models.PositiveIntegerField(verbose_name='año')),
                ('volumen', models.PositiveIntegerField(verbose_name='volumen')),
                ('paginas', models.PositiveIntegerField(verbose_name='paginas')),
                ('pais', models.CharField(max_length=32, verbose_name='pais')),
                ('ciudad', models.CharField(max_length=32, verbose_name='ciudad')),
                ('financiamiento_id', models.ForeignKey(blank='true', on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Financiamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Publicaciones_Autores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Autores', verbose_name='Autor')),
                ('publicacion_doi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Publicaciones', verbose_name='doi')),
            ],
        ),
        migrations.CreateModel(
            name='Rasgos',
            fields=[
                ('rasgos_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, verbose_name='Rasgos')),
            ],
        ),
        migrations.CreateModel(
            name='Registrado_por',
            fields=[
                ('registrado_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, verbose_name='Registrado por')),
                ('email', models.CharField(max_length=32, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='Site3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='nombre')),
                ('manuscritos', models.CharField(blank=True, max_length=32, null=True, verbose_name='manuscritos')),
                ('visitado', models.CharField(blank=True, choices=[('0', 'Si'), ('1', 'No')], max_length=32, null=True, verbose_name='visitado')),
                ('longitud', models.CharField(blank=True, max_length=32, null=True, verbose_name='longitud')),
                ('latitud', models.CharField(blank=True, max_length=32, null=True, verbose_name='latitud')),
                ('altitud', models.CharField(blank=True, max_length=128, null=True, verbose_name='altitud')),
                ('tipo_yacimiento', models.CharField(blank=True, max_length=32, null=True, verbose_name='tipo de yacimiento')),
                ('visibilidad', models.CharField(blank=True, max_length=32, null=True, verbose_name='visibilidad')),
                ('pendiente', models.CharField(blank=True, max_length=32, null=True, verbose_name='pendiente')),
                ('extension_ns', models.PositiveIntegerField(blank=True, null=True, verbose_name='Extensión Norte Sur')),
                ('extension_we', models.PositiveIntegerField(blank=True, null=True, verbose_name='Extensión Este Oeste')),
                ('observacion', models.CharField(blank=True, max_length=2560, null=True, verbose_name='observaciones')),
                ('fecha', models.PositiveIntegerField(blank=True, null=True, verbose_name='Fechado')),
                ('ad_cultural_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Ad_cultural')),
                ('agentes_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Agentes')),
                ('alteracion_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Por_alteracion')),
            ],
        ),
        migrations.CreateModel(
            name='Subtipo',
            fields=[
                ('subtipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, verbose_name='Impacto')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_agente',
            fields=[
                ('agente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, verbose_name='Agente')),
                ('impacto', models.CharField(max_length=32, verbose_name='Impacto')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_deposito',
            fields=[
                ('deposito_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, verbose_name='Tipo deposito')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_fuente_agua',
            fields=[
                ('fuente_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=32, verbose_name='Tipo fuente de agua')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_hallazgo',
            fields=[
                ('hallazgo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, verbose_name='Tipo Hallazgo')),
                ('distribucion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Distribucion_espacial')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_publicaciones',
            fields=[
                ('tipo_pub_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=32, verbose_name='tipo publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_sedimento',
            fields=[
                ('sedimento_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, verbose_name='Sedimiento')),
                ('naturaleza_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Naturaleza')),
            ],
        ),
        migrations.CreateModel(
            name='Vegetacion',
            fields=[
                ('vegetacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, verbose_name='Vegetacion')),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('zona_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, verbose_name='Zona')),
            ],
        ),
        migrations.AddField(
            model_name='subtipo',
            name='tipo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Tipo'),
        ),
        migrations.AddField(
            model_name='site3',
            name='deposito_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Tipo_deposito'),
        ),
        migrations.AddField(
            model_name='site3',
            name='emplazamiento_geo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Emplazamiento_geo'),
        ),
        migrations.AddField(
            model_name='site3',
            name='emplazamiento_sitio_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Emplazamiento_sitio'),
        ),
        migrations.AddField(
            model_name='site3',
            name='evaluacion_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Evaluacion'),
        ),
        migrations.AddField(
            model_name='site3',
            name='funcion_inferida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Funcion_inferida'),
        ),
        migrations.AddField(
            model_name='site3',
            name='hallazgo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Tipo_hallazgo'),
        ),
        migrations.AddField(
            model_name='site3',
            name='imagen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Imagenes'),
        ),
        migrations.AddField(
            model_name='site3',
            name='instrumentos_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Instrumentos'),
        ),
        migrations.AddField(
            model_name='site3',
            name='localidad_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Localidad'),
        ),
        migrations.AddField(
            model_name='site3',
            name='prov_bio_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Provincia_biotica'),
        ),
        migrations.AddField(
            model_name='site3',
            name='publicacion_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Publicaciones'),
        ),
        migrations.AddField(
            model_name='site3',
            name='rasgos_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Rasgos'),
        ),
        migrations.AddField(
            model_name='site3',
            name='registrado_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Registrado_por'),
        ),
        migrations.AddField(
            model_name='site3',
            name='sedimento_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Tipo_sedimento'),
        ),
        migrations.AddField(
            model_name='site3',
            name='vegetacion_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Vegetacion'),
        ),
        migrations.AddField(
            model_name='site3',
            name='zona_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Zona'),
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='tipo_pub_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Tipo_publicaciones'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='sitio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Site3'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='subtipo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Subtipo'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='prov_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Provincia'),
        ),
        migrations.AddField(
            model_name='instituciones_registrado',
            name='registrado_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Registrado_por', verbose_name='registrado por'),
        ),
        migrations.AddField(
            model_name='imagen_objeto',
            name='imagen_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Imagenes'),
        ),
        migrations.AddField(
            model_name='imagen_objeto',
            name='objeto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Objeto'),
        ),
        migrations.AddField(
            model_name='financiamiento_instituciones',
            name='institucion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Instituciones', verbose_name='institucion'),
        ),
        migrations.AddField(
            model_name='distancia_fuente_agua',
            name='fuente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Tipo_fuente_agua'),
        ),
        migrations.AddField(
            model_name='distancia_fuente_agua',
            name='sitio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Site3'),
        ),
        migrations.AddField(
            model_name='distancia_camino',
            name='sitio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Site3'),
        ),
        migrations.AddField(
            model_name='agentes',
            name='agente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Tipo_agente'),
        ),
        migrations.AddField(
            model_name='agentes',
            name='impacto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Impacto'),
        ),
        migrations.AddField(
            model_name='ad_cultural',
            name='periodo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Periodo'),
        ),
    ]
