# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_rental', '0004_auto_20170808_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('componente_id', models.AutoField(primary_key=True, serialize=False)),
                ('componente', models.CharField(max_length=32, verbose_name='componente')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('periodo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, verbose_name='Periodo')),
            ],
        ),
        migrations.RemoveField(
            model_name='ad_cultural',
            name='componentes',
        ),
        migrations.RemoveField(
            model_name='ad_cultural',
            name='periodo',
        ),
        migrations.AddField(
            model_name='ad_cultural',
            name='componente_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Componente', verbose_name='componente_id'),
        ),
        migrations.AddField(
            model_name='ad_cultural',
            name='periodo_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='equipment_rental.Periodo', verbose_name='periodo_id'),
        ),
    ]
